### ISSUE TITLE
Question: Would a Wii U Version of This Application be Possible?

### ISSUE THREAD

**Issue by GK6475** [Lorenzooone/cc3dsfs#8]
A Wii U homebrew version of this application could be useful for playing on the big screen for people that don't have or want to have a computer hooked up to their system. I'm pretty sure that the Wii U has USB 2.1 speeds through its back ports, so it would at least be able to show a 2D image with audio, assuming that the hardware and software could interact with the 3DS. It would also be neat if the bottom and top screens could display separately on the game pad and on the output, and if input redirection (NTR-like, over WiFi) could be used on the gamepad to play games with the touchscreen and controls. So, would it be possible to have a Wii U port, out of curiosity?

**Comment by Lorenzooone** [comment]
You'd need to basically re-implement libusb for Wii U, then decompile FTD3XX and/or FTD2XX to recompile them for that architecture specifically, and finally completely change the current graphical/sound backend to use the proprietary one of the Wii U.

Theoretically possible? Yes.
I'm not going to be the one working on that, though. Since it's going to require an enormous amount of work.

Assuming you could get the data to properly transfer through USB (already not guaranteed/easy), it would be way easier making an application from scratch for it, and just picking some relevant pieces of code from here with certain definitions.

**Comment by GK6475** [comment]
Well, I thought it was a neat idea and I had to ask about it. I would attempt to make something myself but I'm not that skilled at coding in particular. Thanks for the reply, perhaps someone else would be able to do something with the idea.
